a = input('Digite algo:')
print('O tipo primitivo desse valor é:', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanumerico?', a.isalnum())
print('É em maiúsculas?', a.isupper())
print('É em minusculas?', a.islower())
print('Está capitalizada?', a.istitle())